spring.application.name=veloop-rewards-backend
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/veloop_rewards
spring.datasource.username=root
spring.datasource.password=enter_your_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


jwt.secret=${JWT_SECRET}
jwt.expiration=900000



springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html



security.rate-limit.enabled=true

security.rate-limit.login-requests=5
security.rate-limit.login-window-seconds=60


security.rate-limit.withdrawal-requests=5
security.rate-limit.withdrawal-window-seconds=60


security.rate-limit.wallet-mutation-requests=20
security.rate-limit.wallet-mutation-window-seconds=60


security.rate-limit.withdrawal-mutation-requests=20
security.rate-limit.withdrawal-mutation-window-seconds=60


security.rate-limit.max-entries=10000