CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    account_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    level INT NOT NULL DEFAULT 0,
    current_rank VARCHAR(50) DEFAULT NULL,
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);